Update Reporting_RabbitMQ_For_Kubernetes_Issues.md
rabbitmq/support-tools pull request #34
Opened 2022-07-18 12:25 UTC by pstack2021

## Overview of changes

## Assessment of priority

Please delete the answers to the questions below as appropriate. 

For example, for the question: **How blocking is this documentation?:** The acceptable answers are: **Very/Somewhat/Not at all** if your answer is **Very** please delete the remaining answers **Somewhat** and **Not at all**.

**How blocking is this documentation?:** Very/Somewhat/Not at all

**Is there a user waiting on this change?:** Y/N

**Roughly how urgently is this documentation needed:** ASAP/This Week/This Month/At some point

## Links to related issues / PRs / context

2022-07-18 12:30 UTC, michaelklishin requested changes

2022-07-18 12:30 UTC, michaelklishin commented on docs/Reporting_RabbitMQ_For_Kubernetes_Issues.md
> +7.
This empty line breaks list item numbering.

In general, nested lists is something to be avoided in Markdown. I'd suggest turning this list with **bold headers** into a set of sections 

``` md
#### Like This

#### and This

#### that each

 * Can
 * have
 * its own
 * nested
 * list
```

2022-07-19 15:27 UTC, pstack2021 commented
@DanielePalaia please review my changes to ensure they are technically correct before merging into the original document that you sent me for review. 
Many thanks,
Paula.

2022-07-19 15:50 UTC, DanielePalaia approved these changes

2022-07-19 15:51 UTC, DanielePalaia commented
@pstack2021 yes fine for me, I will anyway review it again before sending to support! Thanks!

2022-07-19 22:13 UTC, merged

2022-07-20 09:28 UTC, michaelklishin commented
I will take care of [this formatting suggestion](https://github.com/rabbitmq/support-tools/pull/34#discussion_r923317469).

2022-07-20 12:18 UTC, pstack2021 commented
thank you @michaelklishin