Introduce max_count for checking the queue master
rabbitmq/support-tools pull request #9
Opened 2018-01-29 20:15 UTC by Itxaka

If something fails during movement of a queue, the script would hang
in teh same queue awaiting forever.
This patch introduces a max_count option that can be set so if we reach
the number of retries set it skips waiting for the queue to be changed.

This is useful for unnatended launches in clusters where the number of
queues is high and they are heavily unbalanced, as it can take hours to
change masters and sync all of them, the script can be fired and left alone.

2018-01-29 20:17 UTC, Itxaka commented
@lukebakken not sure about this one. I found out during testing that it was stuck in one queue created by rabbit's PerfTest, and by the time I checked it was on check 800, so it hadent done anything but stuck in there.

Maybe its not a normal usecase for the script so it can be dismissed. Let me know what you think :)

2018-01-29 20:34 UTC, lukebakken requested changes
Thanks! I just have some minor changes to use `bash` syntax.

2018-01-29 20:34 UTC, lukebakken commented on scripts/rebalance-queue-masters
> +declare -r default_max_count=100
Please use `declare -ri` to specify read-only integer

2018-01-29 20:34 UTC, lukebakken commented on scripts/rebalance-queue-masters
> +            while [ $count -lt $max_count ]
`while ((count < max_count))`

2018-01-29 20:34 UTC, lukebakken commented on scripts/rebalance-queue-masters
> +                if [ $count == $max_count ]
`if ((count == max_count))`

2018-01-29 20:34 UTC, lukebakken commented on scripts/rebalance-queue-masters
> +                declare -gr max_count="$OPTARG"
`declare -gri`

2018-01-29 20:34 UTC, lukebakken commented on scripts/rebalance-queue-masters
> +        declare -gr max_count=${default_max_count}
`declare -gri`

2018-01-30 14:36 UTC, Itxaka commented
All comments updated!

2018-01-30 15:40 UTC, lukebakken requested changes
Thanks for making the requested changes @Itxaka. I ran `shellcheck` which shows the following:

```
$ shellcheck scripts/rebalance-queue-masters 

In scripts/rebalance-queue-masters line 88:
            while (( $count < $max_count ))
                     ^-- SC2004: $/${} is unnecessary on arithmetic variables.
                              ^-- SC2004: $/${} is unnecessary on arithmetic variables.


In scripts/rebalance-queue-masters line 90:
                if (( $count == $max_count ))
                      ^-- SC2004: $/${} is unnecessary on arithmetic variables.
                                ^-- SC2004: $/${} is unnecessary on arithmetic variables.
```

2018-02-05 01:06 UTC, lukebakken approved these changes

2018-02-05 01:06 UTC, merged